Ridefiniamo la lista dei riempimenti, ma lo facciamo scrivendo ogni riempimento di seguito per righe (per farlo per colonne avevamo dovuto usare excel...)

In [ ]:


riempimenti = [[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 1, 0, 0],
 [0, 1, 1, 1, 0],
 [0, 1, 1, 0, 1],
 [0, 1, 1, 0, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 0, 1],
 [0, 0, 1, 1, 1],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 1, 0],
 [0, 0, 0, 1, 1]]

print(riempimenti)



[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 1, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 0, 1], [0, 1, 1, 0, 0], [0, 1, 0, 1, 0], [0, 1, 0, 0, 1], [0, 0, 1, 1, 1], [0, 0, 1, 0, 1], [0, 0, 1, 1, 0], [0, 0, 0, 1, 1]]


Importiamo la libreria NumPy che ci permette di manipolare e operare sulle matrici in modo più immediato. 

In [ ]:
import numpy as np

Partendo dalla lista dei riempimenti, definiamo una matrice.
Attenzione, *riempimenti* e *a_ij* sembrano uguali ma **non** lo sono! (controllare le virgole).

In [ ]:
a_ij = np.array(riempimenti)
print(a_ij)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 1 0 0]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [0 1 1 0 0]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 0 1 1 1]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 0 1 1]]


Posso accedere al singolo elemento della matrice. Che cosa stampa il comando di seguito?

In [ ]:
print (a_ij[5][2])

1


Ricordate che vogliamo i riempimenti per colonne, non per righe. Basta fare la trasposta della matrice.

In [ ]:
a_ij = np.transpose(a_ij)
print (a_ij)

[[1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 1 1 1 1 0 0 0 0]
 [0 0 1 0 0 1 1 1 1 0 0 1 1 1 0]
 [0 0 0 1 0 0 1 0 0 1 0 1 0 1 1]
 [0 0 0 0 1 0 0 1 0 0 1 1 1 0 1]]


In [ ]:
import shutil
import sys
import os.path

if not shutil.which("pyomo"):
    !pip install -q pyomo
    assert(shutil.which("pyomo"))

if not (shutil.which("glpk") or os.path.isfile("glpk")):
    if "google.colab" in sys.modules:
        !apt-get install -y -qq glpk-utils
    else:
        try:
            !conda install -c conda-forge glpk 
        except:
            pass

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 75.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 KB 6.0 MB/s eta 0:00:00
Selecting previously unselected package libsuitesparseconfig5:amd64.
(Reading database ... 128285 files and directories currently installed.)
Preparing to unpack .../libsuitesparseconfig5_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libsuitesparseconfig5:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libamd2:amd64.
Preparing to unpack .../libamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libcolamd2:amd64.
Preparing to unpack .../libcolamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libcolamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libglpk40:amd64.
Preparing to unpack .../libglpk40_4.65-2_amd64.deb ...
Unpacking libglpk40:amd64 (4.65-2) ...
Selecting previously unselected package glpk-utils.
Preparing to unpack ...

Vogliamo scrivere un generico modello di set covering con $n$ colonne ed $m$ righe: 

$\min c^t x$

$Ax \ge \bf{1}$

$x \in \{0,1\}^n$

Più in esplicito:

Modello ILP:

$\min \sum_{j=1,\dots,n} c_j x_j$

$ \sum_{j=1,\dots,n} a_{ij} x_j \ge 1 ~~~ i=1,\dots,m$ 

$x_j \in\{0,1\}~~~j=1,\dots,n$

Consideriamo un'istanza in cui abbiamo una riga per ogni oggetto dell'istanza di BPP considerata ieri, tutte le colonne hanno costo pari a $1$, e ogni colonna rappresenta un codifica binaria di un riempimento ammissibile di un bin. Ad esempio, $[0,1,1,0,0]^t$ rappresenta il riempimento che contiene gli oggetti $2$ e $3$.

Istanze BPP: 5 items, pesi $[7,4,1,4,4]$, $W=10$.

In [ ]:
# dati

RIGHE = ['riga_1', 'riga_2', 'riga_3', 'riga_4', 'riga_5'] 
#settimana scorsa erano "materie prime" M



 

In [ ]:
COLONNE = ['c01','c02','c03','c04','c05','c06','c07','c08','c09','c10','c11','c12','c13','c14', 'c15'] 
#settimana scorsa erano "prodotti" P

importiamo la libreria PYOMO

In [ ]:
from pyomo.environ import *

Creiamo modello *concrete*

In [ ]:
setcov = ConcreteModel()  # chiamo il modello setcov


 


Definiamo delle variabili binarie

In [ ]:
setcov.x = Var(COLONNE, within=Binary)

Definiamo la funzione obiettivo ma per farlo definiamo una funzione prende come argomento il modello (chiamato genericamente *mod*) che poi passiamo alla funzione obiettivo come *rule*

In [ ]:
def obj_rule(mod):
    return sum(mod.x[p] for p in COLONNE)
setcov.obj = Objective(rule=obj_rule, sense = minimize )





Allo stesso modo definiamo i vincoli. Innanzitutto definiamo una funzione che prende come argomento il modello (*mod*) e un parametro *m*. 

Attenzione: abbiamo un vincolo per ogni riga, cioé per ogni elemento $r$ della lista $RIGHE$. Il vincolo, definito dalla *rule*, somma su tutte le colonne $c \in COLONNE$

Attenzione: gli elementi della lista righe si chiamano *riga1, riga2,...*; gli elementi della lista colonne si chiamano *c01, c02,...* mentre per accedere correttamente alla matrice *a_ij* dobbiamo specificare gli indici corrispondenti di riga e colonna. Possiamo recuperare l'indice di un elemento *e* in una *LISTA* con comando *LISTA.idex(e)*

In [ ]:
def cover_rule(mod, r):
    return sum(a_ij[RIGHE.index(r)][COLONNE.index(c)]*mod.x[c] for c in COLONNE) >= 1
setcov.cover_const = Constraint(RIGHE, rule=cover_rule)

In [ ]:
SolverFactory('glpk').solve(setcov, tee=True)

GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --write /tmp/tmp46eu4j8a.glpk.raw --wglp /tmp/tmph8l24epd.glpk.glp --cpxlp
 /tmp/tmpestcc6bx.pyomo.lp
Reading problem data from '/tmp/tmpestcc6bx.pyomo.lp'...
/tmp/tmpestcc6bx.pyomo.lp:86: warning: lower bound of variable 'x1' redefined
/tmp/tmpestcc6bx.pyomo.lp:86: warning: upper bound of variable 'x1' redefined
6 rows, 16 columns, 29 non-zeros
15 integer variables, all of which are binary
101 lines were read
Writing problem data to '/tmp/tmph8l24epd.glpk.glp'...
76 lines were written
GLPK Integer Optimizer, v4.65
6 rows, 16 columns, 29 non-zeros
15 integer variables, all of which are binary
Preprocessing...
1 hidden packing inequaliti(es) were detected
5 rows, 15 columns, 28 non-zeros
15 integer variables, all of which are binary
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
Constructing initial basis...
Size of triangular part is 5
Solv

{'Problem': [{'Name': 'unknown', 'Lower bound': 3.0, 'Upper bound': 3.0, 'Number of objectives': 1, 'Number of constraints': 6, 'Number of variables': 16, 'Number of nonzeros': 29, 'Sense': 'minimize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '7', 'Number of created subproblems': '7'}}, 'Error rc': 0, 'Time': 0.011518239974975586}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [ ]:
setcov.pprint()

2 Set Declarations
    cover_const_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {'riga_1', 'riga_2', 'riga_3', 'riga_4', 'riga_5'}
    x_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   15 : {'c01', 'c02', 'c03', 'c04', 'c05', 'c06', 'c07', 'c08', 'c09', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15'}

1 Var Declarations
    x : Size=15, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
        c01 :     0 :   1.0 :     1 : False : False : Binary
        c02 :     0 :   0.0 :     1 : False : False : Binary
        c03 :     0 :   0.0 :     1 : False : False : Binary
        c04 :     0 :   0.0 :     1 : False : False : Binary
        c05 :     0 :   0.0 :     1 : False : False : Binary
        c06 :     0 :   0.0 :     1 : False : False : Binary
        c07 :     0 :   1.0 :     1 : False : False : Binary

In generale, la libreria NumPy implementa le più comuni operazioni su matrici. Oltre alla creazione con *array*, possiamo creare una matrice di zeri con 3 righe e 4 colonne.

In [ ]:
a = np.array([[1, 2, 3, 4], [1, 1, 0, 4],[0, 0, 0, 1]])
matrice_di_zeri = np.zeros((3, 4))
print("a=\n",a)
print("\n")
print("matrice_di_zeri=\n", matrice_di_zeri)


a=
 [[1 2 3 4]
 [1 1 0 4]
 [0 0 0 1]]


matrice_di_zeri=
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Sommare due matrici elemento per elemento, fare il prodotto di due matrici elemento per elemento.

In [ ]:
b=  np.array([[1, 1, 1, 1], [1, 1, 1, 1],[2, 2, 2, 2]])
print ("somma:\n",a+b)
print ("\n prodotto (NB: questo non è il prodotto di matrici!):\n",a*b)

somma:
 [[2 3 4 5]
 [2 2 1 5]
 [2 2 2 3]]

 prodotto (NB: questo non è il prodotto di matrici!):
 [[1 2 3 4]
 [1 1 0 4]
 [0 0 0 2]]


Prodotto di matrici:

In [ ]:
bT = np.transpose(b)
print ("a=\n",a)
print ("\n b =\n",b)
print ("\n bT =\n",bT)
print ("\n prodotto di matrici:\n",a.dot(bT))

a=
 [[1 2 3 4]
 [1 1 0 4]
 [0 0 0 1]]

 b =
 [[1 1 1 1]
 [1 1 1 1]
 [2 2 2 2]]

 bT =
 [[1 1 2]
 [1 1 2]
 [1 1 2]
 [1 1 2]]

 prodotto di matrici:
 [[10 10 20]
 [ 6  6 12]
 [ 1  1  2]]


Possiamo modificare la forma (shape) delle matrici.

In [ ]:
new_a = a.reshape(6,2)
print (new_a)

[[1 2]
 [3 4]
 [1 1]
 [0 4]
 [0 0]
 [0 1]]


Appiattire la matrice.

In [ ]:
print (a.ravel())

[1 2 3 4 1 1 0 4 0 0 0 1]


E fare tante altre operazioni come descritto nella documentazione [https://numpy.org/doc/stable/user/quickstart.html](https://numpy.org/doc/stable/user/quickstart.html)